# -*- coding: utf-8 -*-
"""AlcoholReviews

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbRPgvbrl2K1WP4FrwLRbgq0HSkfgBSe
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import re

# 设置页面配置
st.set_page_config(page_title="酒精笔评论闭环分析", layout="wide")

# --- 1. FEATURE_KEYWORDS 词库 (已包含你提供的精细词汇) ---
FEATURE_KEYWORDS = {
    '颜色种类': {
        '正面': ['many colors', 'lot of colors', 'plenty of colors', 'good range', 'great variety', 'great selection', 'every color', 'all the colors', 'so many options', 'love the large set', 'great number of colors', 'perfect amount of colors', 'huge set of 72', 'full set is amazing', 'good assortment', 'great color selection', 'perfect pastel set', 'good range of skin tones', 'well-curated palette', 'love the color story', 'beautiful assortment of colors', 'has every color I need'],
        '负面': ['limited range', 'not enough colors', 'wish for more', 'missing colors', 'disappointed with selection', 'needs more colors', 'wish for a smaller set', 'too many colors', 'no smaller option', 'forced to buy the large set', 'have to buy the whole set', 'missing key colors', 'no true red', 'needs more grays', 'too many similar colors', 'palette is not useful', 'wish it had more pastels', 'poor color selection', 'needs more skin tones']
    },
    '笔头表现': {
        '正面': ['love the dual tip', 'love the two tips', 'love that it has two sides', 'love the dual nibs', 'great having two tips', 'useful dual tip', 'handy dual tip', 'convenient to have two tips', 'love the brush and fine tip combo', 'love the brush tip', 'great brush nib', 'flexible brush tip', 'soft brush tip', 'love the fine tip', 'precise fine liner', 'perfect for details', 'sharp chisel edge', 'sturdy bullet tip'],
        '负面': ['useless dual tip', 'redundant dual tip', "don't need the dual tip", 'only use one side', 'brush tip frays', 'brush tip split', 'brush tip wore out', 'fine tip is scratchy', 'fine tip dried out', 'chisel tip is too broad', 'chisel tip is too thick', 'too stiff', 'too firm', 'too soft', 'mushy', 'fray', 'fraying', 'split']
    },
    '流畅性与墨水': {
        '正面': ['writes smoothly', 'buttery smooth', 'glides across the page', 'consistent ink flow', 'no skipping', 'no bleed-through', 'zero bleed', 'no ghosting', 'quick dry', 'dry so fast', 'non-toxic', 'no smell', 'odorless', 'no smear', 'smudge proof'],
        '负面': ['scratchy', 'feels scratchy', 'writes dry', 'arrived dried out', 'skips', 'skipping', 'ink skips', 'hard start', 'bleeds through', 'bleed-through is bad', 'ghosting is terrible', 'smears easily', 'smudges easily', 'bad smell', 'strong smell', 'toxic smell', 'leaks', 'leaking ink']
    }
}

# --- 2. 核心逻辑函数 ---
def analyze_closed_loop_with_lexicon(df, keywords):
    # 自动识别列名（防止大小写坑）
    # 检查 Title 和 Review Content 是否存在
    cols = {c.lower(): c for c in df.columns}
    title_col = cols.get('title', 'Title')
    review_col = cols.get('review content', 'Review Content')
    sales_col = cols.get('average monthly sales', 'Average Monthly sales')

    all_pos_phrases = [p for cat in FEATURE_KEYWORDS.values() for p in cat.get('正面', [])]
    all_neg_phrases = [p for cat in FEATURE_KEYWORDS.values() for p in cat.get('负面', [])]

    pos_regex = re.compile(r'\b(' + '|'.join(map(re.escape, all_pos_phrases)) + r')\b', re.IGNORECASE)
    neg_regex = re.compile(r'\b(' + '|'.join(map(re.escape, all_neg_phrases)) + r')\b', re.IGNORECASE)

    results = []
    for kw in keywords:
        # 修改处：使用 title_col 变量
        mask = df[title_col].str.contains(kw, case=False, na=False)
        sub_df = df[mask].copy()
        if sub_df.empty: continue

        total_reviews = len(sub_df)
        # 修改处：使用 review_col 变量
        mention_mask = sub_df[review_col].str.contains(kw, case=False, na=False)
        mention_count = mention_mask.sum()
        mention_rate = (mention_count / total_reviews) * 100 if total_reviews > 0 else 0

        relevant_reviews = sub_df[mention_mask][review_col].astype(str)
        pos_hits = relevant_reviews.apply(lambda x: len(pos_regex.findall(x))).sum()
        neg_hits = relevant_reviews.apply(lambda x: len(neg_regex.findall(x))).sum()

        sentiment_score = (pos_hits - neg_hits) / (pos_hits + neg_hits + 1e-6)

        results.append({
            "关键词": kw,
            "心智提及率(%)": round(mention_rate, 2),
            "情感正向指数": round(sentiment_score, 3),
            "关联产品月销量": int(pd.to_numeric(sub_df[sales_col], errors='coerce').sum()),
            "样本评论量": total_reviews,
            "正面词命中": pos_hits,
            "负面词命中": neg_hits
        })
    return pd.DataFrame(results)

# --- 3. Streamlit UI 布局 ---
st.title("🖌️ 酒精笔卖点闭环反馈分析系统")

# 侧边栏：文件上传
st.sidebar.header("数据上传")
uploaded_file = st.sidebar.file_uploader("上传您的评论数据 (XLSX 或 CSV)", type=["xlsx", "csv"])

if uploaded_file:
    # 自动根据文件后缀识别读取方式
    if uploaded_file.name.endswith('.csv'):
        df = pd.read_csv(uploaded_file)
    else:
        # 确保安装了 openpyxl 库：pip install openpyxl
        df = pd.read_excel(uploaded_file)

    # 侧边栏：关键词设置
    st.sidebar.header("分析设置")
    default_keywords = ['Brush Tip', 'Colors', 'Alcohol', 'Refillable', 'Dual Tip', 'Bleed', 'Blend']
    selected_kws = st.sidebar.multiselect("选择或输入要分析的标题关键词", default_keywords, default=default_keywords)

    if selected_kws:
        res_df = analyze_closed_loop_with_lexicon(df, selected_kws)

        if not res_df.empty:
            # 图表展示
            st.subheader("🔄 卖点闭环归因图谱")
            fig = px.scatter(res_df,
                             x="心智提及率(%)",
                             y="情感正向指数",
                             size="关联产品月销量",
                             color="关键词",
                             text="关键词",
                             hover_data=["正面词命中", "负面词命中", "样本评论量"],
                             range_y=[-1.1, 1.1])

            fig.add_hline(y=0, line_dash="solid", line_color="black")
            fig.add_vline(x=res_df['心智提及率(%)'].mean(), line_dash="dash", annotation_text="平均提及率")

            fig.update_layout(height=600)
            st.plotly_chart(fig, use_container_width=True)

            # 详细表格
            st.subheader("📊 详细维度指标")
            st.dataframe(res_df.sort_values("心智提及率(%)", ascending=False), use_container_width=True)
        else:
            st.warning("所选关键词在数据中未匹配到结果。")
else:
    st.info("👋 请在左侧上传评论数据 CSV 文件开始分析。")
